import AuthContext from '@/context/auth-context'
import ToastContext from '@/context/toast-provider'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import Sidebar from './components/sidebar/sidebar'
import Navbar from './components/navbar/navbar'
import ModalProvider from '@/context/modal-provider'

const roboto = Roboto({ subsets: ['latin'] , weight : ['100','300','400','500','700','900'] })

export const metadata: Metadata = {
  title: 'Notify',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${roboto.className} bg-[#1a1d21] text-gray-300`}>
        <AuthContext>
          <ToastContext/>

          <Sidebar/>
          <Navbar/>
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
